load "../tasks/compile.rake"

RUBY_19 = "ruby19" # Maybe change this?

CLEAN.include('boot.cx')

compile_tasks "vm"

file "boot.cx" => ["boot.rb", "compile.rb"] do |t|
  sh "#{RUBY_19} compile.rb boot boot.rb > #{t.name}"
end

# File dependencies
file 'main.o' => %w( main.c boot.cx )
file 'vm.o' => %w( inst.h vm.c )