require 'rake/clean'

CLEAN.include("boot.rb")
FILES = File.read("order").split("\n")

file "boot.rb" => FILES do |t|
  File.open(t.name, 'w') do |f|
    FILES.each do |file|
      f << "\# == #{file}\n"
      f << File.read(file)
      f << "\n"
    end
  end
end

task :copy do
  cp "boot.rb", "../vm"
end

task :compile => ["boot.rb", :copy]
task :default => :compile
