OPCODES = {
  :nop                 =>  0,
  :getlocal            =>  1,
  :setlocal            =>  2,
  :getspecial          =>  3,
  :setspecial          =>  4,
  :getdynamic          =>  5,
  :setdynamic          =>  6,
  :getinstancevariable =>  7,
  :setinstancevariable =>  8,
  :getclassvariable    =>  9,
  :setclassvariable    => 10,
  :getconstant         => 11,
  :setconstant         => 12,
  :getglobal           => 13,
  :setglobal           => 14,
  :putnil              => 15,
  :putself             => 16,
  :putundef            => 17,
  :putobject           => 18,
  :putstring           => 19,
  :concatstrings       => 20,
  :tostring            => 21,
  :toregexp            => 22,
  :newarray            => 23,
  :duparray            => 24,
  :expandarray         => 25,
  :concatarray         => 26,
  :splatarray          => 27,
  :checkincludearray   => 28,
  :newhash             => 29,
  :newrange            => 30,
  :putnot              => 31,
  :pop                 => 32,
  :dup                 => 33,
  :dupn                => 34,
  :swap                => 35,
  :reput               => 36,
  :topn                => 37,
  :emptstack           => 38,
  :definemethod        => 39,
  :alias               => 40,
  :undef               => 41,
  :defined             => 42,
  :postexe             => 43,
  :trace               => 44,
  :defineclass         => 45,
  :send                => 46,
  :invokesuper         => 47,
  :invokeblock         => 48,
  :leave               => 49,
  :finish              => 50,
  :throw               => 51,
  :jump                => 52,
  :branchif            => 53,
  :branchunless        => 54,
  :setn                => 55,
  
  # my own lil instructions
  :label               => 55

}

class VM
  
end