load "../../tasks/compile.rake"

EXCLUDE_OBJ = ["../../vm/main.o"]

Dir["*_test.c"].each do |file|
  # Create an executable for each _test.c file
  compile_test_tasks file.ext(""), "../../vm", EXCLUDE_OBJ
end

task :before_compile do
  # Build tested project
  cd("../../vm") { sh "rake compile" }
end
